"""EFC protocol constants.

The UUIDs, headers, frame types and timing values come from captures of a
CITYSPORTS WP9 and from the published notes of the Trught EQiSports
protocol project.
"""

from typing import Final

__all__ = [
    "DEFAULT_KEEPALIVE_SECONDS",
    "DEFAULT_RAMP_INTERVAL_SECONDS",
    "DEFAULT_RESPONSE_TIMEOUT_SECONDS",
    "DEFAULT_WRITE_SPACING_SECONDS",
    "MIN_RAMP_INTERVAL_SECONDS",
]

SERVICE_UUID: Final = "ffeeddcc-bbaa-9988-7766-554433221100"
WRITE_CHARACTERISTIC_UUID: Final = "ffeeddcc-bbaa-9988-7766-554433221101"
NOTIFY_CHARACTERISTIC_UUID: Final = "ffeeddcc-bbaa-9988-7766-554433221102"

NAME_PREFIX: Final = "CITYSPORTS"

INBOUND_HEADER: Final = 0x1A
OUTBOUND_HEADER: Final = 0xA1
MAX_FRAME_BYTES: Final = 20

FRAME_STATUS: Final = 0x01
FRAME_COUNTERS: Final = 0x02
FRAME_SPORT_RECORD: Final = 0x04
FRAME_DEVICE_INFO: Final = 0x05

COMMAND_SPEED: Final = 0x01
COMMAND_INCLINE: Final = 0x02
COMMAND_CONTROL: Final = 0x03
COMMAND_SPORT_RECORD: Final = 0x04
COMMAND_DEVICE_INFO: Final = 0x05

CONTROL_START: Final = 0x01
CONTROL_PAUSE: Final = 0x03
CONTROL_STOP: Final = 0x05

STATUS_IMPERIAL_BIT: Final = 0x80
STATUS_CODE_MASK: Final = 0x1F

KM_PER_MILE: Final = 1.609344

ELAPSED_MODULUS: Final = 6000
STEPS_MODULUS: Final = 10000
ENERGY_MODULUS: Final = 10000

DEFAULT_CONNECT_TIMEOUT_SECONDS: Final = 30.0
DEFAULT_RESPONSE_TIMEOUT_SECONDS: Final = 10.0
DEFAULT_KEEPALIVE_SECONDS: Final = 30.0
DEFAULT_WRITE_SPACING_SECONDS: Final = 0.15
DEFAULT_RAMP_INTERVAL_SECONDS: Final = 0.3
MIN_RAMP_INTERVAL_SECONDS: Final = 0.15
